### ISSUE TITLE
[QUESTION]为什么没有upsert/insertOrUpdate方法

### ISSUE THREAD

**Issue by xmsz** [TencentCloud/tencentcloud-sdk-nodejs#102]
背景
- 需要实现存在更新，不存在插入的需求
- 只看到文档里有set，但这个set不符合需求。因为需要自己先查到docId。

需求
- 为什么没有upsert的方法

**Comment by zqfan** [comment]
请到控制台提工单给具体的产品，sdk只是对接口的封装，接口能力缺失，sdk无法补齐
