### ISSUE TITLE
d.ts 中无参数的 API，仍需指定一个空 object 参数才可以正常使用，否则提示对于指定content-type=application/json协议下，请求内容不是合法的Json格式。

### ISSUE THREAD

**Issue by ganlvtech** [TencentCloud/tencentcloud-sdk-nodejs#104]
README 中的示例会报错 `对于指定content-type=application/json协议下，请求内容不是合法的Json格式。`

`client.DescribeZones()` 会报错，必须明确指定空 object `client.DescribeZones({})` 才可以正常使用

```json
{
  "dependencies": {
    "tencentcloud-sdk-nodejs": "^4.0.269",
  }
}
```

相关代码

https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/1c2a020d9e9128469c1eced2f55963a6c7ae80f2/README.md#L34-L66

https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/1c2a020d9e9128469c1eced2f55963a6c7ae80f2/tencentcloud/services/cvm/v20170312/cvm_client.d.ts#L332-L335

https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/1c2a020d9e9128469c1eced2f55963a6c7ae80f2/tencentcloud/services/cvm/v20170312/cvm_models.d.ts#L1167-L1170

https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/1c2a020d9e9128469c1eced2f55963a6c7ae80f2/tencentcloud/common/abstract_client.js#L109

https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/1c2a020d9e9128469c1eced2f55963a6c7ae80f2/tencentcloud/common/http/http_connection.js#L36

https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/1c2a020d9e9128469c1eced2f55963a6c7ae80f2/tencentcloud/common/http/http_connection.js#L124-L141

其中的 `data: params || "",` 可能应该为 `data: params || {},`，`deepRemoveNull` 没有判断本身是否为 `null`

**Comment by WooodHead** [comment]
这个问题导致 readme 里面官方 example 都报错，建议赶紧修一下。
