### ISSUE TITLE
TDMQ没有ReceiveCmqMsg

### ISSUE THREAD

**Issue by Nxys** [TencentCloud/tencentcloud-sdk-nodejs#107]
TDMQ里有SendCmqMsg，为什么没有receive呢？

**Comment by zqfan** [comment]
sdk是对官网发布接口的封装，这说明tdmq并未在官网发布对应接口的文档。
请到官网控制台，工单，提工单给tdmq产品咨询哈。只要他们在官网发布了api文档，sdk就会同步支持。
