### ISSUE TITLE
Any plans on including AbortSignal?

### ISSUE THREAD

**Issue by pubg-suchanpark** [TencentCloud/tencentcloud-sdk-nodejs#121]
Hi, thanks for the nice SDK.

I would like to inject AbortSignal to all requests so that I can cancel the requests any time I want. I am aware that I can control request timeout, but I would want to use AbortSignal because it allows real-time cancellation. 

Here is my trial: https://github.com/pubg-suchanpark/tencentcloud-sdk-nodejs/commit/b6dcb3e30044363b88270154f4e4d842da68dbd9

It doesn't really work because all SDK functions call `this.request` only internally, so I'm not able to inject `RequestOptions`.

Also, I think it's inappropriate to include AbortSignals into `ClientConfig`, because that means I'm able to cancel requests at most once per SDK instance.

Are there plans to include AbortSignal in this library?

**Comment by cyrilluce** [comment]
Currently you can use this hack method after #127 merged
```typescript
const client = new CvmClient()
const ac = new AbortController()
client.request('DescribeZones', null, {
  signal: ac.signal
})
setTimeout(()=>ac.abort(), 100)
```

**Comment by TheNorthMemory** [comment]
Hi there, you may try this new sdk, https://github.com/TheNorthMemory/tenyun . The codes ether js or ts  shall be somthing like this,

```js
import TenYun from 'tenyun';

const tc = new TenYun();

tc.cvm.DescribeZones({}, {cancelToken: () => {}});
```
