### ISSUE TITLE
abstract_client.ts 中的改动导致 HTTP 请求头中包含非法的 token

### ISSUE THREAD

**Issue by kbridge** [TencentCloud/tencentcloud-sdk-nodejs#131]
[参见此处](https://github.com/TencentCloud/tencentcloud-sdk-nodejs/commit/a6491f7a2ba4e44b4d3c3bfcf6893e8cf78cc143?diff=split#r94056596)

**Comment by cyrilluce** [comment]
感谢反馈，已在 #132 中修复，预计下周一更新版本后可用。
