### ISSUE TITLE
这文档写的真是垃圾啊，跟阿里云相差100000倍

### ISSUE THREAD

**Issue by jsmgg** [TencentCloud/tencentcloud-sdk-nodejs#137]

**Comment by zqfan** [comment]
请指出具体希望改进的点，光喷人发泄情绪于事无补

**Comment by jsmgg** [comment]
<img width="924" alt="image" src="https://user-images.githubusercontent.com/16717688/231961813-b6d4cc13-eb76-4080-8b33-f826e43e4c15.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/16717688/231963017-abd52ddd-5861-488e-9398-8756f676c100.png">

<img width="938" alt="image" src="https://user-images.githubusercontent.com/16717688/231963361-2e01a901-2a28-492b-9c7a-81dfb913739d.png">
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/16717688/231963633-60719001-a441-475c-8387-835cd65fda64.png">

**Comment by cnoder-wgh** [comment]
确实确实确实👍

**Comment by rehiy** [comment]
确实有不足的地方，应该给出控制台地址，官方文档地址等。单一的示例不足以覆盖开发者使用场景。

**Comment by zhichengzhu** [comment]
合影😂😂😂
