### ISSUE TITLE
请问cos对应哪个目录

### ISSUE THREAD

**Issue by tashuo** [TencentCloud/tencentcloud-sdk-nodejs#139]

**Comment by tashuo** [comment]
获取签名后的私有bucket的资源地址，请问要怎么做

**Comment by zqfan** [comment]
这个sdk仅包含API3.0范围内的产品和接口，不包含cos的接口，cos因为要兼容aws s3协议，有提供专门的cos sdk，可以参考https://cloud.tencent.com/document/product/436/8629

**Comment by tashuo** [comment]
谢谢
