### ISSUE TITLE
Could not resolve "json-bigint"

### ISSUE THREAD

**Issue by fjc0k** [TencentCloud/tencentcloud-sdk-nodejs#141]
![image](https://github.com/TencentCloud/tencentcloud-sdk-nodejs/assets/13151189/63394842-6cee-42dc-84b3-fb0d73d9d9d1)
![image](https://github.com/TencentCloud/tencentcloud-sdk-nodejs/assets/13151189/96d1b487-0ea3-4900-9b8c-ebb3b8d70a6f)

**Comment by fjc0k** [comment]
回退到 4.0.672 解决问题：
```json
  "resolutions": {
    "tencentcloud-sdk-nodejs-common": "4.0.672"
  },
```
<img width="481" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-nodejs/assets/13151189/c657246b-284a-41c0-8dc7-160a62cb749f">

**Comment by zqfan** [comment]
看起来最新版本已经解决这个问题了，
![image](https://github.com/TencentCloud/tencentcloud-sdk-nodejs/assets/2180987/9dbc2262-ba5e-4dc4-9e6c-657e79e04d96)
