### ISSUE TITLE
小程序中怎么使用

### ISSUE THREAD

**Issue by Jetgege** [TencentCloud/tencentcloud-sdk-nodejs#15]
小程序中怎么使用？

**Comment by BigWolf286** [comment]
应该 是用 云函数 或者 在自己后台调用，  但是我现在遇到签名的问题

**Comment by zqfan** [comment]
@BigWolf286 说的对，API无法跨域，移动端密钥也是问题，所以一般是在后台调用。
签名问题可以参考文档，注意文档中强调的一些细节，以及利用https://console.cloud.tencent.com/api/explorer进行签名验证
