### ISSUE TITLE
官方有支持typescript的打算吗？

### ISSUE THREAD

**Issue by zhou7rui** [TencentCloud/tencentcloud-sdk-nodejs#18]

**Comment by eczn** [comment]
+1 开发的时候非常需要

**Comment by beary** [comment]
建议使用 TypeScript 重构，看看 AWS 家提供的开发套件 https://github.com/aws/aws-cdk 就流口水

**Comment by LuHugo** [comment]
开发的时候用vs code 都没有提示，也没有接口文档，开发的时候去翻的源码，比较烦。强烈建议支持typescript……

**Comment by yhuaqiang** [comment]
还没有支持js/ts. 什么时候支持啊

**Comment by beary** [comment]
我司转 serverless 架构直接上 aws 了，对 sdk 需求比较强的情况下，国内的云厂商没一个像样的，没 promise 没 ts 没文档，整个 aws 架构都被你们抄过来了，就是懒得顺便抄一抄周边，可能只有上新功能才有 kpi 吧。

**Comment by zqfan** [comment]
已经在评估中了

**Comment by pikadun** [comment]
> 已经在评估中了

建议给出一个dts文件就可以了，ts生成的js代码会对性能产生影响

**Comment by Teakowa** [comment]
Any updates?

**Comment by zqfan** [comment]
主干4.x版本已经支持ts
