### ISSUE TITLE
请问如何支持 promise？

### ISSUE THREAD

**Issue by ash0080** [TencentCloud/tencentcloud-sdk-nodejs#2]
看到 AbsoluteClient内置 HttpConnection本身是 Promise，但返回结果居然又包裹成 callback 了，
感觉比较无语

**Comment by lopo1983** [comment]
没人回答吗？我也遇到了同样的问题！

**Comment by lopo1983** [comment]
`const tencentcloud = require("tencentcloud-sdk-nodejs");
// 导入对应产品模块的client models。
const CvmClient = tencentcloud.cvm.v20170312.Client;
const models = tencentcloud.cvm.v20170312.Models;
// 
const Credential = tencentcloud.common.Credential;
// 实例化一个认证对象，入参需要传入腾讯云账户secretId，secretKey
let cred = new Credential("secretId", "secretKey");
const rubbishTencent = (client, name, request) => {
    let promise = new Promise((resolve, reject) => {
        client[name](request, (err, data) => {
            if (err) {
                reject(err)
            } else {
                resolve(data)
            }
        })
    });
    return promise;
}
const DescribeRegions = (callback) => {
    var backJSON = { a: 1 }
    let client = new CvmClient(cred, "ap-shanghai");
    let request = new models.DescribeZoneInstanceConfigInfosRequest();
    rubbishTencent(client, 'DescribeZoneInstanceConfigInfos', request).then(res => {
        console.log(res)
    })
};
DescribeRegions()`

**Comment by lopo1983** [comment]
``
const tencentcloud = require("tencentcloud-sdk-nodejs");
// 导入对应产品模块的client models。
const CvmClient = tencentcloud.cvm.v20170312.Client;
const models = tencentcloud.cvm.v20170312.Models;
// 
const Credential = tencentcloud.common.Credential;
// 实例化一个认证对象，入参需要传入腾讯云账户secretId，secretKey
let cred = new Credential("secretId", "secretKey");
const rubbishTencent = (client, name, request) => {
    let promise = new Promise((resolve, reject) => {
        client[name](request, (err, data) => {
            if (err) {
                reject(err)
            } else {
                resolve(data)
            }
        })
    });
    return promise;
}
const DescribeRegions = (callback) => {
    var backJSON = { a: 1 }
    let client = new CvmClient(cred, "ap-shanghai");
    let request = new models.DescribeZoneInstanceConfigInfosRequest();
    rubbishTencent(client, 'DescribeZoneInstanceConfigInfos', request).then(res => {
        console.log(res)
    })
};
DescribeRegions()

**Comment by ash0080** [comment]
嗯 我也是自行包裹了下 凑合用用

**Comment by PandaTsui** [comment]
同求，什么时候sdk直接支持promise

**Comment by Chenyueli** [comment]
升级4.+版本，已支持promise

**Comment by zqfan** [comment]
主干4.x版本已经支持
