### ISSUE TITLE
HMAC-SHA256 签名方式有问题 ?

### ISSUE THREAD

**Issue by eczn** [TencentCloud/tencentcloud-sdk-nodejs#23]
SCF 传函数的时候需要传 zip 文件，根据文档里的描述这里可以采用传 Base64 的方式进行传输。 

然而，base64 很长，最后得到的响应是签名无效。。。。 

![image](https://user-images.githubusercontent.com/13131724/62820410-7ab9db80-bb96-11e9-970d-77c4580b5c39.png)

而代码里默认走的是 hmac256:

![image](https://user-images.githubusercontent.com/13131724/62820416-9329f600-bb96-11e9-9f4b-5dd667ee948b.png)

看起来是 Hmac 256 的实现有问题，能定位看看问题不？

**Comment by eczn** [comment]
https://cloud.tencent.com/document/api/583/18586

这是创建SCF函数的接口。

**Comment by zqfan** [comment]
签名v3尚未合入主干：https://github.com/TencentCloud/tencentcloud-sdk-nodejs/tree/signature3

**Comment by eczn** [comment]
> 签名v3尚未合入主干：https://github.com/TencentCloud/tencentcloud-sdk-nodejs/tree/signature3

好吧，我这里目前走 cos 上传代码了。

**Comment by shynome** [comment]
@zqfan 现在 signature3 的分支能用 v3 签名吗

**Comment by shynome** [comment]
signature3 分支 v3 签名 `GeneralBasicOCRRequest` 失败: 
The provided credentials could not be validated. Please check your signature is correct.
