### ISSUE TITLE
TC3-HMAC-SHA256 支持了吗？

### ISSUE THREAD

**Issue by shynome** [TencentCloud/tencentcloud-sdk-nodejs#25]
java 的 sdk 已经支持了, nodejs 的应该也快了吧

**Comment by VictoryDong** [comment]
+1

**Comment by Juliiii** [comment]
+1

**Comment by Juliiii** [comment]
诶，我觉得这个有必要赶快支持了啊。现在通过这个包去调一些云api，如果包大的话，接口肯定崩的。自己手写签名算法，耗时耗力又重复造轮子。这样对开发者极其不友好。

**Comment by Kacoo** [comment]
原来nodejs的sdk还不支持TC3-HMAC-SHA256
┭┮﹏┭┮

**Comment by VictoryDong** [comment]
什么时候才可以支持呢

**Comment by shenghanqin** [comment]
还是不支持呗？官方也不更新一下？

**Comment by shenghanqin** [comment]
我基于录音识别里面提供的功能就可以做到啦 https://cloud.tencent.com/document/product/1093/39964里面的nodejs，当前下载地址是https://sdk-1256085166.cos.ap-shanghai.myqcloud.com/nodejs_record_asr_sdk_v3.zip

**Comment by shynome** [comment]
如果 6 月份还没有的话, 我会提交一份 pr

**Comment by luohao8023** [comment]
还没支持啊

**Comment by shenghanqin** [comment]
@luohao8023 这个仓库有另外一个v3的分支，不知为何没有合并到master分支上。

**Comment by luohao8023** [comment]
@shenghanqin 找到啦，可以用。真棒，非常感谢。

**Comment by shenghanqin** [comment]
> @shenghanqin 找到啦，可以用。真棒，非常感谢。

当然，可能新的master分支上会有新的功能，只需要拷贝到v3分支即可。自己用这样就够用了

**Comment by yugasun** [comment]
推荐使用 https://www.npmjs.com/package/@tencent-sdk/capi

**Comment by shenghanqin** [comment]
> 也可以尝试下 https://www.npmjs.com/package/@tencent-sdk/capi

感谢。

**Comment by zqfan** [comment]
3.x分支和4.x主干都已支持
