### ISSUE TITLE
SDK不支持「自定义监控」

### ISSUE THREAD

**Issue by valaxy** [TencentCloud/tencentcloud-sdk-nodejs#3]
RT..
用的还是挺多的

**Comment by valaxy** [comment]
https://cloud.tencent.com/document/api/397/4247
自定义监控-数据上报还只支持主账号上报，有计划什么时候能切到V3吗？

**Comment by zqfan** [comment]
有计划但暂无明确上线日期

**Comment by zqfan** [comment]
已支持。详见官网文档，sdk changelog以及源码
