### ISSUE TITLE
删除短信模板报错

### ISSUE THREAD

**Issue by hoperce** [TencentCloud/tencentcloud-sdk-nodejs#36]
`{
	"Response": {
		"Error": {
			"Code": "InternalError.JsonParseFail",
			"Message": "request json body parse fail"
		},
		"RequestId": "927a4b10-592f-4a43-8e1a-afe606148aeb"
	}
}`

**Comment by zqfan** [comment]
你的参数不是合法的json，短信后台报错了。SDK无法解决这种问题，请到控制台提咨询工单给短信业务。
