### ISSUE TITLE
in vue2.6.10 and webpack4.29.6 project ，Can't resolve 'fs'

### ISSUE THREAD

**Issue by cybibo** [TencentCloud/tencentcloud-sdk-nodejs#37]
$: npm run dev

./node_modules/_request@2.88.2@request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/Users/ryan/main/works/jxlife/Jiyibao_mobile/node_modules/_request@2.88.2@request/lib'

**Comment by shenghanqin** [comment]
这个是给nodejs用的，不是给前端用的。你最好是使用nodejs接入腾讯云，然后以request api的方式来请求nodejs的服务。

**Comment by zqfan** [comment]
确实如此，另一个问题是目前不支持跨域，即使是腾讯云官网也是前端js发往后端，后端处理逻辑再请求api
