### ISSUE TITLE
TryLipstickPic 方法能否加个return

### ISSUE THREAD

**Issue by funjobs** [TencentCloud/tencentcloud-sdk-nodejs#39]
https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/master/tencentcloud/fmu/v20191213/fmu_client.js
能否提供了同步方法，小程序中的云函数没办法获取异步回调方法的返回值

**Comment by zqfan** [comment]
请参考下readme里的示例，可以用callback的方式获取到返回。我不太懂nodejs，开发人员看了这个issue说这里没必要加return。有没有更详细的解释，报错什么的贴一下看看@funjobs

**Comment by funjobs** [comment]
在小程序云函数中使用该sdk，没办法获取返回值。因为云函数就是异步回调

**Comment by zqfan** [comment]
由于太久没有反馈，先关闭，后续有更新可以重新打开
