### ISSUE TITLE
SCF invoke example

### ISSUE THREAD

**Issue by ivangergo3** [TencentCloud/tencentcloud-sdk-nodejs#45]
I will add a new example of how SCF invoke works

**Comment by ivangergo3** [comment]
The code is ready, can someone help me put, by creating a branch/adding me to the contributors?

**Comment by zqfan** [comment]
you can just create a pull request, maintainer will review it.

**Comment by zqfan** [comment]
close it because no update for a long time. feel free to reopen it.
