### ISSUE TITLE
请升级 https-proxy-agent 版本

### ISSUE THREAD

**Issue by xieziyu** [TencentCloud/tencentcloud-sdk-nodejs#47]
2.x 版本的 https-proxy-agent 会因其依赖的低版本 agent-base 使得 `https.request` 被覆写，进而导致使用 `got` 的项目会无法发出请求: 
```
connect ECONNREFUSED 127.0.0.1:443
````

#### Related Issue
https://github.com/sindresorhus/got/issues/951

#### Related Fix
https://github.com/TooTallNate/node-agent-base/pull/36

**Comment by zqfan** [comment]
已经在beta版本测试中

**Comment by wong2** [comment]
什么时候发布呢，又被坑了。。

**Comment by zqfan** [comment]
> 什么时候发布呢，又被坑了。。

请试用下v4.x版本，注意和v3.x是不兼容的

**Comment by wong2** [comment]
@zqfan 用的是v4.x，https-proxy-agent 还是 2.x 啊 https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/master/package.json#L29

**Comment by kejiweixun** [comment]
> > 什么时候发布呢，又被坑了。。
> 
> 请试用下v4.x版本，注意和v3.x是不兼容的

请问有升级计划了吗？遇到一样的问题，用了 got 就不能用这个，用了这个就不能用 got

**Comment by lizhihao001** [comment]
这问题还没解决吗？

**Comment by wong2** [comment]
@zqfan

**Comment by tsutsumishinhi** [comment]
同样有这个问题，agent-base版本太低导致shopify-api-node报错。
https://github.com/MONEI/Shopify-api-node/issues/397
@zqfan

**Comment by zqfan** [comment]
开发人员已经在主干升级了版本，请使用最新版本验证下。如有问题，可再开启本issue
