### ISSUE TITLE
cmq消息相关的方法呢，只有队列的

### ISSUE THREAD

**Issue by yeongjet** [TencentCloud/tencentcloud-sdk-nodejs#52]
`tencentcloud\cmq\v20190304\cmq_client.js` 这个文件只有队列相关的没有消息相关
是只能用订阅的这种方式了吗

**Comment by zqfan** [comment]
因为cmq特殊的产品形态，消息的发送和消费，cmq提供了自己的sdk来处理，详情请参考官网cmq文档
