### ISSUE TITLE
hi，tencenter 在腾讯示例中underfind tencentcloud.common.Credential

### ISSUE THREAD

**Issue by yichengxian** [TencentCloud/tencentcloud-sdk-nodejs#54]
tencentcloud-sdk-nodejs 依赖版本：^4.0.3，
腾讯云示例node code url：https://console.cloud.tencent.com/api/explorer?Product=ft&Version=2020-03-04&Action=SwapGenderPic&SignVersion=
示例code如下：
`const tencentcloud = require("tencentcloud-sdk-nodejs");

const FtClient = tencentcloud.ft.v20200304.Client;
const models = tencentcloud.ft.v20200304.Models;

const Credential = tencentcloud.common.Credential;
const ClientProfile = tencentcloud.common.ClientProfile;
const HttpProfile = tencentcloud.common.HttpProfile;

let cred = new Credential("", "");
let httpProfile = new HttpProfile();
httpProfile.endpoint = "ft.tencentcloudapi.com";
let clientProfile = new ClientProfile();
clientProfile.httpProfile = httpProfile;
let client = new FtClient(cred, "ap-guangzhou", clientProfile);

let req = new models.SwapGenderPicRequest();

let params = {
    "GenderInfos": [
        {
            "Gender": 1
        }
    ]
};
req.from_json_string(JSON.stringify(params));

client.SwapGenderPic(req, function(errMsg, response) {
    if (errMsg) {
        console.log(errMsg);
        return;
    }
    console.log(response.to_json_string());
});`
异常如下：const Credential = tencentcloud.common.Credential;   
TypeError: Cannot read property 'Credential' of undefined;
查询源码中并无 common 请问是npm冲突还是?
源码导入模块如下：
`export { aa } from "./aa";
export { aai } from "./aai";
export { af } from "./af";
export { afc } from "./afc";
export { ame } from "./ame";
export { ams } from "./ams";
export { apigateway } from "./apigateway";
export { as } from "./as";
export { asr } from "./asr";
export { batch } from "./batch";
export { bda } from "./bda";
export { billing } from "./billing";
export { bizlive } from "./bizlive";
export { bm } from "./bm";
export { bmeip } from "./bmeip";
export { bmlb } from "./bmlb";
export { bmvpc } from "./bmvpc";
export { bri } from "./bri";
export { cam } from "./cam";
export { captcha } from "./captcha";
export { cat } from "./cat";
export { cbs } from "./cbs";
export { ccc } from "./ccc";
export { cdb } from "./cdb";
export { cdn } from "./cdn";
export { cds } from "./cds";
export { cfs } from "./cfs";
export { cfw } from "./cfw";
export { chdfs } from "./chdfs";
export { cim } from "./cim";
export { cis } from "./cis";
export { ckafka } from "./ckafka";
export { clb } from "./clb";
export { cloudaudit } from "./cloudaudit";
export { cloudhsm } from "./cloudhsm";
export { cme } from "./cme";
export { cmq } from "./cmq";
export { cms } from "./cms";
export { cpdp } from "./cpdp";
export { cr } from "./cr";
export { cvm } from "./cvm";
export { cwp } from "./cwp";
export { cws } from "./cws";
export { cynosdb } from "./cynosdb";
export { dayu } from "./dayu";
export { dbbrain } from "./dbbrain";
export { dc } from "./dc";
export { dcdb } from "./dcdb";
export { domain } from "./domain";
export { drm } from "./drm";
export { ds } from "./ds";
export { dts } from "./dts";
export { ecc } from "./ecc";
export { ecdn } from "./ecdn";
export { ecm } from "./ecm";
export { emr } from "./emr";
export { es } from "./es";
export { facefusion } from "./facefusion";
export { faceid } from "./faceid";
export { fmu } from "./fmu";
export { ft } from "./ft";
export { gaap } from "./gaap";
export { gme } from "./gme";
export { gs } from "./gs";
export { gse } from "./gse";
export { habo } from "./habo";
export { hcm } from "./hcm";
export { iai } from "./iai";
export { ic } from "./ic";
export { ie } from "./ie";
export { iir } from "./iir";
export { iot } from "./iot";
export { iotcloud } from "./iotcloud";
export { iotexplorer } from "./iotexplorer";
export { iottid } from "./iottid";
export { iotvideo } from "./iotvideo";
export { kms } from "./kms";
export { lighthouse } from "./lighthouse";
export { live } from "./live";
export { lp } from "./lp";
export { mariadb } from "./mariadb";
export { memcached } from "./memcached";
export { mgobe } from "./mgobe";
export { mongodb } from "./mongodb";
export { monitor } from "./monitor";
export { mps } from "./mps";
export { ms } from "./ms";
export { msp } from "./msp";
export { mvj } from "./mvj";
export { nlp } from "./nlp";
export { npp } from "./npp";
export { ocr } from "./ocr";
export { organization } from "./organization";
export { partners } from "./partners";
export { postgres } from "./postgres";
export { redis } from "./redis";
export { rkp } from "./rkp";
export { rp } from "./rp";
export { scf } from "./scf";
export { smpn } from "./smpn";
export { sms } from "./sms";
export { soe } from "./soe";
export { solar } from "./solar";
export { sqlserver } from "./sqlserver";
export { ssl } from "./ssl";
export { ssm } from "./ssm";
export { sts } from "./sts";
export { taf } from "./taf";
export { tag } from "./tag";
export { tav } from "./tav";
export { tbaas } from "./tbaas";
export { tbm } from "./tbm";
export { tbp } from "./tbp";
export { tcaplusdb } from "./tcaplusdb";
export { tcb } from "./tcb";
export { tcex } from "./tcex";
export { tci } from "./tci";
export { tcr } from "./tcr";
export { tdmq } from "./tdmq";
export { tia } from "./tia";
export { ticm } from "./ticm";
export { tics } from "./tics";
export { tiems } from "./tiems";
export { tiia } from "./tiia";
export { tione } from "./tione";
export { tiw } from "./tiw";
export { tke } from "./tke";
export { tkgdq } from "./tkgdq";
export { tms } from "./tms";
export { tmt } from "./tmt";
export { trtc } from "./trtc";
export { tsf } from "./tsf";
export { tts } from "./tts";
export { vod } from "./vod";
export { vpc } from "./vpc";
export { wss } from "./wss";
export { youmall } from "./youmall";
export { yunjing } from "./yunjing";
export { yunsou } from "./yunsou";
`

**Comment by Chenyueli** [comment]
https://console.cloud.tencent.com/api/explore 控制台目前生成是示例依赖的sdk版本是3.x 版本。而你装了4.x版本sdk，所以报错。

解决方案一：安装3.x版本sdk
npm install tencentcloud-sdk-nodejs@3.0.266 --save 
解决方案二：用4.x 新的方式调用，调用方式 详细参考 [readme.md ](https://github.com/TencentCloud/tencentcloud-sdk-nodejs)

后续：/api/explore控制台即将发布 sdk 4.x版本示例。届时推荐使用4.x版本（支持typescript功能）

**Comment by yichengxian** [comment]
> 看描述是由于，api/explore 控制台生成是示例依赖的sdk版本是3.x 版本。而你装了4.x版本sdk，所以报错。
> 
> 解决方案一（推荐）： 使用4.x版本sdk， api/explore 下午已经发布4.x示例版本，重新访问[控制台](https://console.cloud.tencent.com/api/explore)获取示例代码即可。
> 
> 解决方案二：安装3.x版本sdk
> npm install tencentcloud-sdk-nodejs@3.0.266 --save

好的，这个问题，已经处理完毕

**Comment by ruandao** [comment]
你这个问题的处理方式有问题，你应该更新页面文档
要不然后续还有人会踩坑。。。

**Comment by dingtwo** [comment]
踩坑+1，记录一下，文档没有更新
https://cloud.tencent.com/document/product/866/34681#.E7.AC.AC.E4.B8.89.E6.AD.A5.EF.BC.9A.E9.9B.86.E6.88.90.E6.96.87.E5.AD.97.E8.AF.86.E5.88.AB-sdk
