### ISSUE TITLE
The "original" argument must be of type Function

### ISSUE THREAD

**Issue by Richar-Dada** [TencentCloud/tencentcloud-sdk-nodejs#62]
在Ubuntu 系统部署项目，报 The "original" argument must be of type Function 错误，使用的是阿里云服务器。在Windows开发电脑没这个报错。

项目情况：eggjs搭建的项目，依赖如下
"@alicloud/sms-sdk": "^1.0.8",
    "ali-oss": "^6.12.0",
    "cheerio": "^1.0.0-rc.2",
    "egg": "^2.0.0",
    "egg-cors": "^2.0.0",
    "egg-jwt": "^3.1.7",
    "egg-multipart": "^2.10.3",
    "egg-mysql": "^3.0.0",
    "egg-redis": "^2.0.0",
    "egg-scripts": "^2.5.0",
    "egg-sequelize": "^5.0.0",
    "egg-validate": "^1.0.0",
    "egg-view-nunjucks": "^2.1.6",
    "excel-export": "^0.5.1",
    "js-base64": "^2.4.3",
    "jsonwebtoken": "^8.1.1",
    "mocha": "^4.1.0",
    "moment": "^2.21.0",
    "mysql2": "^2.2.5",
    "node-excel-export": "^1.4.3",
    "tencentcloud-sdk-nodejs": "^4.0.44"

**Comment by caoxingshu** [comment]
解决了吗？我在electron-vue里面导入SDK出现了类似的错误

**Comment by whatisth** [comment]
升级一下你的pm2版本

**Comment by Richar-Dada** [comment]
> 解决了吗？我在electron-vue里面导入SDK出现了类似的错误

我把sdk下载到项目用 解决了

**Comment by cyrilluce** [comment]
此sdk仅能用于nodejs环境，不能用于浏览器
