### ISSUE TITLE
"babel-eslint"  ， "eslint-plugin-react" 这两个包应该放到DevDependencies中去

### ISSUE THREAD

**Issue by greper** [TencentCloud/tencentcloud-sdk-nodejs#63]
"babel-eslint"  ， "eslint-plugin-react" 这两个包应该放到DevDependencies中去
转移过去之后 npm install --production  可以减少20个依赖包

**Comment by medz** [comment]
就是，用起来太老火了。。。乱依赖东西，烦死了
