### ISSUE TITLE
看样子是依赖了 libdom 的 dts 文件，可以拿掉换个吗 ?

### ISSUE THREAD

**Issue by eczn** [TencentCloud/tencentcloud-sdk-nodejs#71]
![image](https://user-images.githubusercontent.com/13131724/108965858-62e27380-76b8-11eb-8b74-10459db2b48c.png)

node 上我一般不配置 libdom 的依赖...

**Comment by rekey** [comment]
遇到同样问题，node环境下可以通过引入全局d.ts设置File，可是总感觉不对。

**Comment by zqfan** [comment]
这个应该是生成时候的问题，这个字段被解释为File类型，但是却并未定义
