### ISSUE TITLE
ClientConfig中的可选字段profile.language，如果不填写会报错

### ISSUE THREAD

**Issue by wildfire810** [TencentCloud/tencentcloud-sdk-nodejs#72]
使用的sms.v20190711.Client
按照文档，profile和profile.language是可选字段，但是如果不传入的话，会报错
        this.profile = {
            signMethod: (profile && profile.signMethod) || "TC3-HMAC-SHA256",
            httpProfile: Object.assign({
                reqMethod: "POST",
                endpoint: null,
                protocol: "https://",
                reqTimeout: 60,
            }, profile && profile.httpProfile),
            language: profile.language,//这一行报错
        };
实际上就是没判断是否传了profile对象，就直接取值了。因此直接给profile一个空对象，事实上代码也能过。

另外，为什么v20210111里面没有可用的对象？

**Comment by victorykong** [comment]
这里希望官方尽快修复下吧，细节问题，看源码才看到

**Comment by ganlvtech** [comment]
https://github.com/TencentCloud/tencentcloud-sdk-nodejs/issues/87
https://github.com/TencentCloud/tencentcloud-sdk-nodejs/issues/76
