### ISSUE TITLE
4.0.88版本的npm包dependencies不正确

### ISSUE THREAD

**Issue by zenxds** [TencentCloud/tencentcloud-sdk-nodejs#73]
npm上的版本package.json为

```
"dependencies": {
    "tencentcloud-sdk-nodejs-common": "^1.1.5"
  },
```

跟git代码中的dependencies不一致，导致production环境的某些包比如`tslib`会找不到

**Comment by zqfan** [comment]
收到，我们核实下

**Comment by WANGMUXIAN** [comment]
> npm上的版本package.json为
> 
> ```
> "dependencies": {
>     "tencentcloud-sdk-nodejs-common": "^1.1.5"
>   },
> ```
> 
> 跟git代码中的dependencies不一致，导致production环境的某些包比如`tslib`会找不到

请查收zenxds@gmail.com邮件

**Comment by zyf0330** [comment]
@zqfan 你好，我看最新的 4.0.446 版本还是没有 tslib 依赖，这个问题还没有解决吗？

**Comment by cyrilluce** [comment]
> @zqfan 你好，我看最新的 4.0.446 版本还是没有 tslib 依赖，这个问题还没有解决吗？

具体是哪个包？我检查了4.0.446的依赖，是有tslib的

**Comment by zyf0330** [comment]
> > @zqfan 你好，我看最新的 4.0.446 版本还是没有 tslib 依赖，这个问题还没有解决吗？
> 
> 具体是哪个包？我检查了4.0.446的依赖，是有tslib的

这个包 tencentcloud-sdk-nodejs-captcha

**Comment by cyrilluce** [comment]
> > > @zqfan 你好，我看最新的 4.0.446 版本还是没有 tslib 依赖，这个问题还没有解决吗？
> > 
> > 
> > 具体是哪个包？我检查了4.0.446的依赖，是有tslib的
> 
> 这个包 tencentcloud-sdk-nodejs-captcha

有包版本吗？我检查了最近的包，依赖的common都是声明为 `^4.0.xxx`的，应该会自动安装最新版的common包

建议你升级一下 `tencentcloud-sdk-nodejs-captcha`
```
npm i tencentcloud-sdk-nodejs-captcha@latest
```

**Comment by zyf0330** [comment]
@cyrilluce `tencentcloud-sdk-nodejs-captcha` 的 latest 版本是 4.0.492，依旧没有 `tslib` 依赖。

不过，我刚搞懂你的意思。common 包的确声明了 tslib 依赖，但是这个包本身也依赖了 `tslib`。隐式使用依赖的依赖是有问题的，它自己也需要声明。
