### ISSUE TITLE
建议项目按业务模块拆分发布

### ISSUE THREAD

**Issue by yugasun** [TencentCloud/tencentcloud-sdk-nodejs#74]
当前项目将所有业务模块都发布到同一个 npm 库，用户如果单独只是想使用某个模块，比如 `apigateway`，却需要全量安装，整个包大小有 `23.6M`，如下截图：

![image](https://user-images.githubusercontent.com/8536173/112439541-30459c80-8d84-11eb-98f9-db71a98301ee.png)

可以通过 `lerna` 工具来管理，发包均带有命名空间，比如 `@tencentcloud/apigateway`，这样用户可根据个人需求，来选择安装所需要的业务模块，可以大大精简项目代码体积。

**Comment by zqfan** [comment]
已经按产品分包了，不知道是否满足你的要求
https://github.com/TencentCloud/tencentcloud-sdk-nodejs#%E9%80%9A%E8%BF%87-npm-%E5%AE%89%E8%A3%85
如上引用方式会将腾讯云所有产品sdk下载到本地，可以将tencentcloud-sdk-nodejs换成tencentcloud-sdk-nodejs-cvm/cbs/vpc等，即可引用特定产品的sdk，代码中可将require("tencentcloud-sdk-nodejs")改为require("tencentcloud-sdk-nodejs-cvm/cbs/vpc")，其余不变，可参考示例，可大大节省存储空间。

**Comment by Ccptsoap** [comment]
Duplicate of #

> 已经按产品分包了，不知道是否满足你的要求 https://github.com/TencentCloud/tencentcloud-sdk-nodejs#%E9%80%9A%E8%BF%87-npm-%E5%AE%89%E8%A3%85 如上引用方式会将腾讯云所有产品sdk下载到本地，可以将tencentcloud-sdk-nodejs换成tencentcloud-sdk-nodejs-cvm/cbs/vpc等，即可引用特定产品的sdk，代码中可将require("tencentcloud-sdk-nodejs")改为require("tencentcloud-sdk-nodejs-cvm/cbs/vpc")，其余不变，可参考示例，可大大节省存储空间。

有产品列表吗，单纯看后缀看不出是什么产品。

**Comment by zqfan** [comment]
> Duplicate of #
> 
> > 已经按产品分包了，不知道是否满足你的要求 https://github.com/TencentCloud/tencentcloud-sdk-nodejs#%E9%80%9A%E8%BF%87-npm-%E5%AE%89%E8%A3%85 如上引用方式会将腾讯云所有产品sdk下载到本地，可以将tencentcloud-sdk-nodejs换成tencentcloud-sdk-nodejs-cvm/cbs/vpc等，即可引用特定产品的sdk，代码中可将require("tencentcloud-sdk-nodejs")改为require("tencentcloud-sdk-nodejs-cvm/cbs/vpc")，其余不变，可参考示例，可大大节省存储空间。
> 
> 有产品列表吗，单纯看后缀看不出是什么产品。

https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/master/products.md
