### ISSUE TITLE
这个地方导致我 使用 captcha.v20190722.Client 报错

### ISSUE THREAD

**Issue by notbucai** [TencentCloud/tencentcloud-sdk-nodejs#76]
**我必须将profile作为一个必填项，否则将提示错误**

https://github.com/TencentCloud/tencentcloud-sdk-nodejs/blob/60d74f06313121b6699b420a59e31f5cc5f7769c/src/common/abstract_client.ts#L84

"tencentcloud-sdk-nodejs": "^4.0.90",

```
const Client = captcha.v20190722.Client;
 this.captcha = new Client({
      credential: {
        secretId: this.configService.captcha.appID,
        secretKey: this.configService.captcha.appSecret
      },
      region: "",
      profile: {}
    });
```
Cannot read property 'language' of undefined +14ms
TypeError: Cannot read property 'language' of undefined
    at new AbstractClient (/xxxx/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:50:31)

ps: 其实我觉得这一块有太多的 `&&` 做判断了，这将在开发过程都可能会存在一些问题

**Comment by ganlvtech** [comment]
https://github.com/TencentCloud/tencentcloud-sdk-nodejs/issues/87
